### ISSUE TITLE
issue with sample:Counties data for FIP 06095

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/geo-data-portal#244] opened 2016-11-05 18:52 UTC
The full dataset errors with `"General Error: found non-noded intersection between LINESTRING ( 38.179 -121.665, 38.1772 -121.6632 ) and LINESTRING ( 38.1772 -121.6631, 38.1785 -121.6673 ) [ (38.17724482758621, -121.66324482758621, NaN) ]"`

The culprit is Solano County in CA, which is FIPS code 06095. 06095 has four polygons and `Counties.3369` is the one that causes this error.

a reproducible example is to use the following in the POST:
```XML
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<wps:Execute xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" service="WPS" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsExecute_request.xsd">
<ows:Identifier>
gov.usgs.cida.gdp.wps.algorithm.FeatureWeightedGridStatisticsAlgorithm
</ows:Identifier>
<wps:DataInputs>
<wps:Input>
<ows:Identifier>SUMMARIZE_TIMESTEP</ows:Identifier>
<wps:Data>
<wps:LiteralData>false</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>SUMMARIZE_FEATURE_ATTRIBUTE</ows:Identifier>
<wps:Data>
<wps:LiteralData>false</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>TIME_START</ows:Identifier>
<wps:Data>
<wps:LiteralData>2010-11-01T00:00:00.000Z</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>TIME_END</ows:Identifier>
<wps:Data>
<wps:LiteralData>2010-12-01T00:00:00.000Z</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>GROUP_BY</ows:Identifier>
<wps:Data>
<wps:LiteralData>STATISTIC</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>DATASET_URI</ows:Identifier>
<wps:Data>
<wps:LiteralData>dods://cida.usgs.gov/thredds/dodsC/prism</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>FEATURE_ATTRIBUTE_NAME</ows:Identifier>
<wps:Data>
<wps:LiteralData>FIPS</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>STATISTICS</ows:Identifier>
<wps:Data>
<wps:LiteralData>MEAN</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>DELIMITER</ows:Identifier>
<wps:Data>
<wps:LiteralData>COMMA</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>DATASET_ID</ows:Identifier>
<wps:Data>
<wps:LiteralData>ppt</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>REQUIRE_FULL_COVERAGE</ows:Identifier>
<wps:Data>
<wps:LiteralData>false</wps:LiteralData>
</wps:Data>
</wps:Input>
<wps:Input>
<ows:Identifier>FEATURE_COLLECTION</ows:Identifier>
<wps:Reference xlink:href="http://cida.usgs.gov/gdp/geoserver/wfs">
<wps:Body>
<wfs:GetFeature xmlns:gml="http://www.opengis.net/gml" xmlns:wfs="http://www.opengis.net/wfs" outputFormat="text/xml; subtype=gml/3.1.1" service="WFS" version="1.1.0">
<wfs:Query typeName="sample:Counties">
<wfs:PropertyName>the_geom</wfs:PropertyName>
<wfs:PropertyName>FIPS</wfs:PropertyName>
<ogc:Filter>
<ogc:GmlObjectId gml:id="Counties.3369"/>
</ogc:Filter>
</wfs:Query>
</wfs:GetFeature>
</wps:Body>
</wps:Reference>
</wps:Input>
</wps:DataInputs>
<wps:ResponseForm>
<wps:ResponseDocument status="true" storeExecuteResponse="true">
<wps:Output asReference="true">
<ows:Identifier>OUTPUT</ows:Identifier>
</wps:Output>
</wps:ResponseDocument>
</wps:ResponseForm>
</wps:Execute>
```

**Comment by dblodgett-usgs** [comment] 2016-11-06 00:57
This issue should be fixed now. 

Original looked like:
![screen shot 2016-11-05 at 7 41 26 pm](https://cloud.githubusercontent.com/assets/1492803/20034575/6f4f73ac-a390-11e6-91a0-acce864f1fdf.png)

It now looks like:
![screen shot 2016-11-05 at 7 41 46 pm](https://cloud.githubusercontent.com/assets/1492803/20034579/7e198d82-a390-11e6-8b2a-ebb28bdf50c1.png)

This is a totally mysterious issue with some geometries that is reported related to the Java Topology Suite, which the GDP uses, but no clear fix is in the message board logs and other things I find about it. Usually you can zoom in and see some tightt geometry that can be relaxed and it's fixed. 

I put the new shapefile on artifactory and deployed it to all three tiers. The reproducible example works now. Thanks for the super complete debug and report!!

**Closed by dblodgett-usgs** 2016-11-06 00:57 UTC

**Comment by jread-usgs** [comment] 2016-11-06 01:34
Thanks for the fix @dblodgett-usgs

**Comment by dblodgett-usgs** [comment] 2016-11-06 01:35
NP!
